export const JRPC_METHODS = {
  COMMITMENT_REQUEST: 'TOPRFCommitmentRequest',
  AUTHENTICATE_REQUEST: 'TOPRFAuthenticateRequest',
};

export const COMMIT_RESPONSE_THRESHOLD = 4;
export const NEW_USER_AUTHENTICATION_THRESHOLD = 4;
export const EXISTING_USER_AUTHENTICATION_THRESHOLD = 3;
