export const JRPC_METHODS = {
  COMMITMENT_REQUEST: 'TOPRFCommitmentRequest',
  AUTHENTICATE_REQUEST: 'TOPRFAuthenticateRequest',
  STORE_KEY_SHARES_REQUEST: 'TOPRFStoreKeyShareRequest',
  RESET_RATE_LIMIT_REQUEST: 'TOPRFResetRateLimitRequest',
  TOPRF_EVAL_REQUEST: 'TOPRFEvalRequest',
};

export const COMMIT_RESPONSE_THRESHOLD = 4;
export const NEW_USER_AUTHENTICATION_THRESHOLD = 4;
export const EXISTING_USER_AUTHENTICATION_THRESHOLD = 3;
export const PREPARE_SHARES_THRESHOLD = 4;
