export const JRPC_METHODS = {
  COMMITMENT_REQUEST: 'TOPRFCommitmentRequest',
  AUTHENTICATE_REQUEST: 'TOPRFAuthenticateRequest',
  STORE_KEY_SHARES_REQUEST: 'TOPRFStoreKeyShareRequest',
  RESET_RATE_LIMIT_REQUEST: 'TOPRFResetRateLimitRequest',
  TOPRF_EVAL_REQUEST: 'TOPRFEvalRequest',
  GET_PUB_KEY_REQUEST: 'TOPRFGetPubKeyRequest',
};

export const COMMIT_RESPONSE_THRESHOLD = 4;
export const NEW_USER_AUTHENTICATION_THRESHOLD = 4;
export const EXISTING_USER_AUTHENTICATION_THRESHOLD = 3;
export const GENERATE_SHARE_THRESHOLD = 3;
export const FIRST_KEY_INDEX = 1;
