export type AuthenticationParams = {
  // for now we only support one idToken, in future we will support multiple to remove commitment call
  // so leaving it as an array for future use
  idTokens: string[];
  endpoints: string[];
  indexes: number[];
  verifier: string;
  verifierID: string;
  password: string;
};

export type NodeAuthToken = {
  /**
   * The token issued by the node on verifying the idToken
   */
  nodeAuthToken: string;
  /**
   * The index of the node that issued the token
   */
  nodeIndex: number;
};

export type NodeAuthTokens = NodeAuthToken[];

export type AuthData = {
  authTokens: NodeAuthTokens;
  encKey: string;
}

export type AuthenticationResult = {
  /**
   * The auth data obtain during authentication.
   */
  authData: AuthData;
};

export type StoreSecretDataParams = {
  /**
   * The auth data obtained during authentication.
   */
  authData: AuthData;
  /**
   * The secret data in hex encoding.
   */
  secretData: string;
};

export type FetchSecretDataParams = {
  /**
   * The auth data obtained during authentication.
   */
  authData: AuthData;
};

export type FetchSecretDataResult = {
  /**
   * The encryption key which is used to decrypt the secret data.
   * This key is generated by client and threshold shared with the nodes using TOPRF protocol.
   */
  encKey: string;
  /**
   * The secret data to be fetched
   */
  secretData: string[];
};

export type ChangePasswordParams = {
  /**
   * The auth data obtained during authentication.
   */
  authData: AuthData;
  /**
   * The new password of the user
   */
  newPassword: string;
};

export type ChangePasswordResult = {
  /**
   * The new auth data after changing the password.
   */
  newAuthData: AuthData;
};

export type IMetamaskSecretBackup = {
  authenticate: (params: AuthenticationParams) => Promise<AuthenticationResult>;

  changePassword: (params: ChangePasswordParams) => Promise<ChangePasswordResult>;

  storeSecretData: (params: StoreSecretDataParams) => Promise<void>;

  fetchSecretData: (params: FetchSecretDataParams) => Promise<FetchSecretDataResult>;
};
