export type JWTVerificationParams = {
  // for now we only support one idToken, in future we will support multiple to remove commitment call
  // so leaving it as an array for future use
  idTokens: string[];
  endpoints: string[];
  indexes: number[];
  verifier: string;
  verifierID: string;
};

export type NodeAuthToken = {
  /**
   * The token issued by the node on verifying the idToken
   */
  nodeAuthToken: string;
  /**
   * The index of the node that issued the token
   */
  nodeIndex: number;
};

export type JWTVerificationResult = {
  /**
   * The tokens issued by the nodes on verifying the idTokens
   */
  nodeAuthTokens: NodeAuthToken[];
  /**
   * The public key of the share if the user is an existing user
   */
  existingEncKeyPublicData?: {
    pubKeyX: string;
    pubKeyY: string;
    keyIndex: number;
  };
  /**
   * Whether the user is an existing user
   */
  isExistingUser: boolean;
};

export type RegisterNewSecretParams = {
  /**
   * The tokens issued by the nodes on verifying the idTokens
   */
  nodeAuthTokens: NodeAuthToken[];
  /**
   * The array of secret data to be registered
   * For ex: it can be array of SRPs or wallet etc.
   */
  secretData: string[];
};

export type RegisterNewSecretResult = {
  /**
   * The encryption key which is used to decrypt the secret data.
   * This key is generated by client and threshold shared with the nodes using TOPRF protocol.
   */
  encKey: string;
};

export type FetchSecretDataParams = {
  /**
   * The tokens issued by the nodes on verifying the idTokens
   */
  nodeAuthTokens: NodeAuthToken[];
  /**
   * The password of the user
   * TODO: can we have it as more general term like "userSecret"
   */
  password: string;
};

export type FetchSecretDataResult = {
  /**
   * The encryption key which is used to decrypt the secret data.
   * This key is generated by client and threshold shared with the nodes using TOPRF protocol.
   */
  encKey: string;
  /**
   * The secret data to be fetched
   */
  secretData: string[];
};
export type UpdateEncKeyParams = {
  /**
   * The tokens issued by the nodes on verifying the idTokens
   */
  nodeAuthTokens: NodeAuthToken[];
  /**
   * The new password of the user
   */
  newPassword: string;
} & (
  | { encKey: string; oldPassword?: never }
  | { encKey?: never; oldPassword: string }
);

export type UpdateEncKeyResult = {
  /**
   * The new encryption key which is used to decrypt the secret data.
   * This key is generated by client and threshold shared with the nodes using TOPRF protocol.
   */
  newEncKey: string;
};

export type UpdateSecretDataParams = {
  /**
   * The tokens issued by the nodes on verifying the idTokens
   */
  nodeAuthTokens: NodeAuthToken[];
  /**
   * Existing encryption key which is used to decrypt the secret data.
   */
  encKey: string;
  /**
   * The new secret data to be updated,
   * This data will be merged with existing secret data.
   */
  newSecretData: string[];
};

export type MetamaskTOPRFAuth = {
  verifyIdToken: (
    params: JWTVerificationParams,
  ) => Promise<JWTVerificationResult>;
  registerNewSecret: (
    params: RegisterNewSecretParams,
  ) => Promise<RegisterNewSecretResult>;
  fetchSecretData: (
    params: FetchSecretDataParams,
  ) => Promise<FetchSecretDataResult>;
  updateEncKey: (params: UpdateEncKeyParams) => Promise<UpdateEncKeyResult>;
  updateSecretData: (params: UpdateSecretDataParams) => Promise<void>;
};
