export type AuthenticationParams = {
  // for now we only support one idToken, in future we will support multiple to remove commitment call
  // so leaving it as an array for future use
  idTokens: string[];
  endpoints: string[];
  indexes: number[];
  verifier: string;
  verifierID: string;
};

export type NodeAuthToken = {
  /**
   * The token issued by the node on verifying the idToken
   */
  nodeAuthToken: string;
  /**
   * The index of the node that issued the token
   */
  nodeIndex: number;
};

type NodeAuthTokens = NodeAuthToken[];

export type AuthenticationResult = {
  /**
   * The tokens issued by the nodes on verifying the idTokens
   */
  nodeAuthTokens: NodeAuthTokens;
  /**
   * The public key of the share if the user is an existing user
   */
  existingEncKeyPublicData?: {
    pubKeyX: string;
    pubKeyY: string;
    keyIndex: number;
  };
  /**
   * Whether the user is an existing user
   */
  isExistingUser: boolean;
};

export type StoreSecretDataParams = {
  /**
   * The tokens issued by the nodes on verifying the idTokens
   */
  nodeAuthTokens: NodeAuthTokens;
  /**
   * The encryption key under which the secret data will be encrypted.
  */
  encKey: string;
  /**
   * The secret data in hex encoding.
   */
  secretData: string;
};

export type RegisterNewSecretResult = {
  /**
   * The encryption key which is used to decrypt the secret data.
   * This key is generated by client and threshold shared with the nodes using TOPRF protocol.
   */
  encKey: string;
};

export type FetchSecretDataParams = {
  /**
   * The tokens issued by the nodes on verifying the idToken.
   */
  nodeAuthTokens: NodeAuthTokens;
  /**
   * The password of the user.
   */
  password: string;
};

export type FetchSecretDataResult = {
  /**
   * The encryption key which is used to decrypt the secret data.
   * This key is generated by client and threshold shared with the nodes using TOPRF protocol.
   */
  encKey: string;
  /**
   * The secret data to be fetched
   */
  secretData: string[];
};

export type CreateEncKeyParams = {
  /**
   * The tokens issued by the nodes on verifying the idToken.
   */
  nodeAuthTokens: NodeAuthTokens;
  /**
   * The password of the user.
   */
  password: string;
};

export type CreateEncKeyResult = {
  /**
   * The encryption key which is used to decrypt the secret data. This key is
   * generated by client and threshold shared with the nodes using TOPRF
   * protocol.
   */
  encKey: string;
};

export type RecoverEncKeyParams = {
  /**
   * The tokens issued by the nodes on verifying the idToken.
   */
  nodeAuthTokens: NodeAuthTokens;
  /**
   * The password of the user.
   */
  password: string;
};

export type RecoverEncKeyResult = {
  /**
   * The encryption key which is used to decrypt the secret data. This key is
   * generated by client and threshold shared with the nodes using TOPRF
   * protocol.
   */
  encKey: string;
};

export type UpdateEncKeyParams = {
  /**
   * The tokens issued by the nodes on verifying the idTokens
   */
  nodeAuthTokens: NodeAuthTokens;
  /**
   * The new password of the user
   */
  newPassword: string;
  /**
   * The old encryption key of the user
   */
  oldEncKey: string;
  /**
   * The old password of the user
   */
  oldPassword: string;
};

export type UpdateEncKeyResult = {
  /**
   * The new encryption key which is used to decrypt the secret data.
   * This key is generated by client and threshold shared with the nodes using TOPRF protocol.
   */
  newEncKey: string;
};

export type UpdateSecretDataParams = {
  /**
   * The tokens issued by the nodes on verifying the idTokens
   */
  nodeAuthTokens: NodeAuthTokens;
  /**
   * Existing encryption key which is used to decrypt the secret data.
   */
  encKey: string;
  /**
   * The new secret data to be updated,
   * This data will be merged with existing secret data.
   */
  newSecretData: string[];
};

export type IMetamaskTOPRFAuth = {
  authenticate: (
    params: AuthenticationParams,
  ) => Promise<AuthenticationResult>;

  createEncKey: (params: CreateEncKeyParams) => Promise<CreateEncKeyResult>;

  recoverEncKey: (params: RecoverEncKeyParams) => Promise<RecoverEncKeyResult>;

  updateEncKey: (params: UpdateEncKeyParams) => Promise<UpdateEncKeyResult>;

  storeSecretData: (
    params: StoreSecretDataParams,
  ) => Promise<RegisterNewSecretResult>;

  fetchSecretData: (
    params: FetchSecretDataParams,
  ) => Promise<FetchSecretDataResult>;
};
